"""Build a local ATT&CK-technique-to-D3FEND-technique mapping cache.

The script reads the Enterprise ATT&CK techniques already exported to
``data/mitre_attack.json`` and asks the official D3FEND inferred-relationship
API for each technique and sub-technique.  The result is optimized for this
application: duplicate inference paths are grouped below each D3FEND
technique, while the paths themselves are retained for traceability.
"""

from __future__ import annotations

import argparse
import json
from concurrent.futures import ThreadPoolExecutor, as_completed
from datetime import UTC, datetime
from pathlib import Path
from typing import Any
from urllib.error import HTTPError, URLError
from urllib.request import Request, urlopen

DEFAULT_ATTACK_DATA_PATH = Path("data/mitre_attack.json")
DEFAULT_OUTPUT_PATH = Path("data/attack_d3fend_mappings.json")
DEFAULT_URL_TEMPLATE = "https://d3fend.mitre.org/api/offensive-technique/attack/{id}.json"


def parse_arguments() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--attack-data",
        type=Path,
        default=DEFAULT_ATTACK_DATA_PATH,
        help="ATT&CK matrix JSON generated by fetch_mitre_attack.py.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT_PATH,
        help="Destination JSON file (default: data/attack_d3fend_mappings.json).",
    )
    parser.add_argument(
        "--workers",
        type=int,
        default=8,
        help="Maximum simultaneous D3FEND requests (default: 8).",
    )
    parser.add_argument("--timeout", type=int, default=60, help="HTTP timeout in seconds.")
    return parser.parse_args()


def load_attack_techniques(path: Path) -> dict[str, dict[str, object]]:
    """Return every unique parent technique and sub-technique in the matrix."""
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError as error:
        raise RuntimeError(f"ATT&CK data file does not exist: {path}") from error
    except json.JSONDecodeError as error:
        raise RuntimeError(f"ATT&CK data file is not valid JSON: {path}") from error

    tactics = payload.get("tactics") if isinstance(payload, dict) else None
    if not isinstance(tactics, list):
        raise RuntimeError("ATT&CK data does not contain a tactics list.")

    techniques: dict[str, dict[str, object]] = {}
    for tactic in tactics:
        if not isinstance(tactic, dict):
            continue
        tactic_name = tactic.get("name")
        for technique in tactic.get("techniques", []):
            if not isinstance(technique, dict):
                continue
            add_attack_technique(techniques, technique, tactic_name)
            for subtechnique in technique.get("subtechniques", []):
                if isinstance(subtechnique, dict):
                    add_attack_technique(techniques, subtechnique, tactic_name)

    if not techniques:
        raise RuntimeError("No ATT&CK techniques were found in the ATT&CK data file.")
    return dict(sorted(techniques.items()))


def add_attack_technique(
    techniques: dict[str, dict[str, object]], technique: dict[str, object], tactic_name: object
) -> None:
    """Add a technique once, retaining every tactic where it occurs."""
    technique_id = technique.get("technique_id")
    name = technique.get("name")
    if not isinstance(technique_id, str) or not isinstance(name, str):
        return

    record = techniques.setdefault(
        technique_id,
        {
            "technique_id": technique_id,
            "name": name,
            "is_subtechnique": bool(technique.get("is_subtechnique")),
            "tactics": set(),
        },
    )
    if isinstance(tactic_name, str):
        tactic_names = record["tactics"]
        assert isinstance(tactic_names, set)
        tactic_names.add(tactic_name)


def fetch_mapping(technique_id: str, timeout: int) -> dict[str, Any]:
    """Fetch the official D3FEND mapping document for one ATT&CK technique."""
    url = DEFAULT_URL_TEMPLATE.format(id=technique_id)
    request = Request(url, headers={"User-Agent": "intelgenz-api/0.1"})
    try:
        with urlopen(request, timeout=timeout) as response:  # noqa: S310 - known MITRE URL.
            payload = json.loads(response.read())
    except (HTTPError, URLError, TimeoutError, json.JSONDecodeError) as error:
        raise RuntimeError(f"{technique_id}: {error}") from error

    if not isinstance(payload, dict):
        raise RuntimeError(f"{technique_id}: D3FEND did not return a JSON object.")
    return payload


def binding_value(binding: dict[str, Any], name: str) -> str | None:
    value = binding.get(name)
    if not isinstance(value, dict):
        return None
    text = value.get("value")
    return text if isinstance(text, str) else None


def build_defensive_techniques(document: dict[str, Any]) -> list[dict[str, object]]:
    """Group D3FEND's repeated inference bindings by defensive technique ID."""
    off_to_def = document.get("off_to_def", {})
    results = off_to_def.get("results", {}) if isinstance(off_to_def, dict) else {}
    bindings = results.get("bindings", []) if isinstance(results, dict) else []
    grouped: dict[str, dict[str, object]] = {}

    for binding in bindings:
        if not isinstance(binding, dict):
            continue
        d3fend_id = binding_value(binding, "def_tech_id")
        d3fend_name = binding_value(binding, "def_tech_label")
        if d3fend_id is None or d3fend_name is None:
            continue

        technique = grouped.setdefault(
            d3fend_id,
            {
                "d3fend_id": d3fend_id,
                "name": d3fend_name,
                "parent_technique": binding_value(binding, "def_tech_parent_label"),
                "tactics": set(),
                "inference_paths": [],
            },
        )
        tactics = technique["tactics"]
        assert isinstance(tactics, set)
        tactic = binding_value(binding, "def_tactic_label")
        if tactic:
            tactics.add(tactic)

        path = {
            "defensive_artifact": binding_value(binding, "def_artifact_label"),
            "defensive_artifact_relationship": binding_value(binding, "def_artifact_rel_label"),
            "offensive_artifact": binding_value(binding, "off_artifact_label"),
            "offensive_artifact_relationship": binding_value(binding, "off_artifact_rel_label"),
        }
        paths = technique["inference_paths"]
        assert isinstance(paths, list)
        if path not in paths:
            paths.append(path)

    normalized: list[dict[str, object]] = []
    for d3fend_id in sorted(grouped):
        technique = grouped[d3fend_id]
        tactics = technique.pop("tactics")
        assert isinstance(tactics, set)
        technique["tactics"] = sorted(tactics)
        paths = technique["inference_paths"]
        assert isinstance(paths, list)
        paths.sort(key=lambda path: json.dumps(path, sort_keys=True))
        normalized.append(technique)
    return normalized


def write_json(output_path: Path, payload: dict[str, object]) -> None:
    """Write JSON atomically so a failed refresh never corrupts the old file."""
    output_path.parent.mkdir(parents=True, exist_ok=True)
    temporary_path = output_path.with_suffix(f"{output_path.suffix}.tmp")
    temporary_path.write_text(
        json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
    )
    temporary_path.replace(output_path)


def main() -> None:
    arguments = parse_arguments()
    if arguments.workers < 1:
        raise RuntimeError("--workers must be at least 1.")

    attack_techniques = load_attack_techniques(arguments.attack_data)
    documents: dict[str, dict[str, Any]] = {}
    failures: list[str] = []
    with ThreadPoolExecutor(max_workers=arguments.workers) as executor:
        futures = {
            executor.submit(fetch_mapping, technique_id, arguments.timeout): technique_id
            for technique_id in attack_techniques
        }
        for future in as_completed(futures):
            technique_id = futures[future]
            try:
                documents[technique_id] = future.result()
            except RuntimeError as error:
                failures.append(str(error))

    if failures:
        preview = "; ".join(sorted(failures)[:10])
        raise RuntimeError(
            f"D3FEND mapping refresh failed for {len(failures)} techniques: {preview}"
        )

    mappings: dict[str, object] = {}
    for technique_id, attack_technique in attack_techniques.items():
        tactics = attack_technique["tactics"]
        assert isinstance(tactics, set)
        mappings[technique_id] = {
            "attack": {
                "technique_id": technique_id,
                "name": attack_technique["name"],
                "is_subtechnique": attack_technique["is_subtechnique"],
                "tactics": sorted(tactics),
            },
            "d3fend_techniques": build_defensive_techniques(documents[technique_id]),
        }

    payload: dict[str, object] = {
        "schema_version": "1.0",
        "source": {
            "name": "MITRE D3FEND inferred relationships API",
            "url_template": DEFAULT_URL_TEMPLATE,
            "retrieved_at": datetime.now(UTC).isoformat(),
            "attack_data": str(arguments.attack_data),
            "attack_technique_count": len(attack_techniques),
        },
        "mappings": mappings,
    }
    write_json(arguments.output, payload)
    print(f"Wrote {len(mappings)} ATT&CK-to-D3FEND mappings to {arguments.output}")


if __name__ == "__main__":
    main()
